"""add_user_memories

Revision ID: 6b7de2bc9ce1
Revises: 
Create Date: 2026-06-08 08:51:47.106929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7de2bc9ce1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User identifier — client-side UUID (future: FK → users.id)'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Fact category: personal | preference | project | relationship | context'),
    sa.Column('key', sa.String(length=255), nullable=False, comment="Short label, e.g. 'User's name', 'Preferred language'"),
    sa.Column('content', sa.Text(), nullable=False, comment="Full fact sentence, e.g. 'User's name is Alice, a backend engineer'"),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Extraction confidence 0.0–1.0'),
    sa.Column('source_conversation_id', sa.UUID(), nullable=True, comment='Conversation that produced this memory'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete — inactive memories are not injected into prompts'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_memories_category'), 'user_memories', ['category'], unique=False)
    op.create_index(op.f('ix_user_memories_source_conversation_id'), 'user_memories', ['source_conversation_id'], unique=False)
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=False)
    op.add_column('conversations', sa.Column('user_id', sa.UUID(), nullable=True, comment='User identifier — client-side UUID (future: FK → users.id)'))
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_column('conversations', 'user_id')
    op.drop_index(op.f('ix_user_memories_user_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_source_conversation_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_category'), table_name='user_memories')
    op.drop_table('user_memories')
    # ### end Alembic commands ###
